import { readdirSync, statSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const srcDir = path.resolve(__dirname, '../src')
const componentsDir = path.resolve(srcDir, 'components')
const uiDir = path.resolve(componentsDir, 'ui')

function collectComponentExports() {
  const entries = readdirSync(componentsDir)
  const exports = []

  for (const entry of entries.sort()) {
    if (entry === 'ui')
      continue

    const fullPath = path.resolve(componentsDir, entry)
    const stats = statSync(fullPath)

    if (stats.isFile() && entry.endsWith('.vue')) {
      const componentName = entry.replace(/\.vue$/, '')
      exports.push(`export { default as ${componentName} } from './components/${entry}'`)
    }
  }

  if (statSync(uiDir, { throwIfNoEntry: false })?.isDirectory()) {
    const uiEntries = readdirSync(uiDir)
      .filter(name => statSync(path.resolve(uiDir, name)).isDirectory())
      .sort()

    for (const dir of uiEntries) {
      exports.push(`export * from './components/ui/${dir}'`)
    }
  }

  exports.push(`\nexport { cn } from './lib/utils'`)

  return exports
}

const exportLines = collectComponentExports()
const banner = '// This file is auto-generated by scripts/sync-exports.js\n\n'

writeFileSync(path.resolve(srcDir, 'index.ts'), `${banner}${exportLines.join('\n')}\n`)
